### ISSUE TITLE
Getting NaN type of startRating in event.subscribe 

### ISSUE THREAD

**Issue by RajatTem** [melwinVincent/ionic3-star-rating#2]
When I am printing value on console I am getting NaN of startRating from event.subscribe

Example:
this.event.subscribe('star-rating:changed', (starRating) => {
      console.log(starRating);
    });

output:
NaN

**Comment by melwinVincent** [comment]
hi @RajatTem : Could you please provide further details. 
You can verify your codes comparing this online demo : https://stackblitz.com/edit/ionic3-star-rating

**Comment by RajatTem** [comment]
Hi @melwinVincent I was facing browser specific issue, I am using firefox in this browser when I change rating  I am getting NaN on my console.
Every thing working fine in other browser thank you for your time  I am closing this issue.

**Comment by melwinVincent** [comment]
Hi @RajatTem : Thank you for pointing out the exact reason for this issue. I have fixed this issue and updated the package. Please download the latest version by running the command -
 `npm i ionic3-star-rating@1.1.4`  and check in Firefox.

The click event target was same in chrome & safari, but it was different in Firefox.
So I just made a patch. ref : [https://github.com/melwinVincent/ionic3-star-rating/commit/0dbbd9a9cc4496b07064731147d546ceca5bd70a.](https://github.com/melwinVincent/ionic3-star-rating/commit/0dbbd9a9cc4496b07064731147d546ceca5bd70a.)

Thanks for your support.
I'm closing this issue.
