### ISSUE TITLE
not working with ionic 4

### ISSUE THREAD

**Issue by DILEEP-YADAV** [melwinVincent/ionic3-star-rating#6]
not working with ionic 4

**Comment by MELAS007** [comment]
not working with ionic 4

**Comment by QaisAlkhateeb** [comment]
I'm using Ionic 4, to make it working I just changed **'ionic3-star-rating-component.ts'**:
**change:**
import { Events } from 'ionic-angular'
**to:**
import { Events } from '@ionic/angular';

**Comment by MELAS007** [comment]
Does it work??? @QaisAlkhateeb

**Comment by QaisAlkhateeb** [comment]
Yes

**Comment by MELAS007** [comment]
@QaisAlkhateeb could you share your code? bcz I did it and it doesn't work!!! :(

**Comment by QaisAlkhateeb** [comment]
**stars-rating.component.html**
```html
<div class="ionic3-star-rating">
  <button *ngFor="let index of [0,1,2,3,4]" id="{{index}}" type="button" ion-button icon-only
    (click)="changeRating($event)">
    <ion-icon [ngStyle]="{'color':index < this.Math.round(this.parseFloat(rating)) ? activeColor : defaultColor }"
      name="{{index < this.Math.round(this.parseFloat(rating)) ? activeIcon : defaultIcon}}"></ion-icon>
  </button>
</div>
```

**stars-rating.component.scss**
```css
.ionic3-star-rating{
    button {
        background-color: white;
      ion-icon {
        font-size: 1.0rem;
      }
    }
}
```

**stars-rating.component.ts**
```typescript
import { Component, OnInit, Input } from '@angular/core';
import { Events } from '@ionic/angular';

@Component({
  selector: 'app-stars-rating',
  templateUrl: './stars-rating.component.html',
  styleUrls: ['./stars-rating.component.scss']
})
export class StarsRatingComponent implements OnInit {

  @Input()
  rating: number = 3;
  @Input()
  readonly: string = "false";
  @Input()
  activeColor : string = '#488aff';
  @Input()
  defaultColor : string = '#f4f4f4';
  @Input()
  activeIcon : string = 'ios-star';
  @Input()
  defaultIcon : string = 'ios-star-outline';
  Math: any;
  parseFloat : any;

  constructor(private events : Events) {
    this.Math = Math;
    this.parseFloat = parseFloat;
  }

  changeRating(event){

    if(this.readonly && this.readonly === "true") return;
    // event is different for firefox and chrome
    this.rating = event.target.id ? parseInt(event.target.id) + 1 : parseInt(event.target.parentElement.id) + 1;
    // subscribe this event to get the changed value in ypour parent compoanent 
    this.events.publish('star-rating:changed', this.rating);
  }
  ngOnInit() {
  }

}
```

I add this component to a shared module and expose it, then simply import the shared module and every thing is working:

![52968568_357208411565437_7399091305013313536_n](https://user-images.githubusercontent.com/25031218/53423520-2822a380-39ea-11e9-9c35-b6d8eb1b3756.jpg)

I hope this help you

**Comment by bruno-py** [comment]
I'm glad you shared your solution! I struggled so much with the shadow dom.

**Comment by MELAS007** [comment]
@QaisAlkhateeb Thanks for your code! that is I did and it isnot still working!!!:( 
I'm using Ionic 4....

**Comment by jrcollado88** [comment]
I'm trying it and doesn't work. After creating and export the component. How do you use it in your ionic page?

**Comment by MELAS007** [comment]
@QaisAlkhateeb how did you use in your page?

**Comment by bruno-py** [comment]
I created a repository as an example:
https://github.com/bruno-py/ionic4-star-rating

One change I made was adding an "size" input attribute to the component so it could be easier to change the font-size of the icons.

**Comment by QaisAlkhateeb** [comment]
that's my code:
```html
<app-stars-rating activeIcon="ios-star" defaultIcon="ios-star-outline" activeColor="#488aff"
defaultColor="#f4f4f4" readonly="true" [rating]="question[att]">
</app-stars-rating>
```

**Comment by jrcollado88** [comment]
> I created a repository as an example:
> https://github.com/bruno-py/ionic4-star-rating
> 
> One change I made was adding an "size" input attribute to the component so it could be easier to change the font-size of the icons.

Thanks a lot for the example. Works like a charm. 

One more thing, I put the component inside the page folder. Is there any way to add the component to be used in any page without copy the component in each one? I have tried and doesn't work 😖

**Comment by melwinVincent** [comment]
@DILEEP-YADAV @MELAS007 @QaisAlkhateeb @bruno-py @jrcollado88 

I have made a new component for ionic-4.
Tested and verified

Please check
npm : https://www.npmjs.com/package/ionic4-star-rating
github : https://github.com/melwinVincent/ionic4-star-rating

Thanks for your support
Melwin Vincent C.
